targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - "lib/src/**/domain/**.dart"

      json_serializable:
        generate_for:
          include:
            - "lib/src/**/domain/**.dart"

      riverpod_generator:
        generate_for:
          include:
            - "lib/src/**/application/**.dart"
            - "lib/src/**/data/**.dart"

      go_router_builder:
        generate_for:
          include:
            - "lib/src/routing/**.dart"