name: lm_labs_utils
description: "Reusable utilities for Flutter apps, packages, and plugins to encourage good coding practices"
repository: https://github.com/glemartret/lm_labs_utils
issue_tracker: https://github.com/glemartret/lm_labs_utils/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
version: 1.1.7

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.24.0"

dependencies:
  connectivity_plus: ^6.1.4
  dio: ^5.8.0+1
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.2
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.0.0
  hooks_riverpod: ^2.6.1
  i18n_extension: ^15.0.5
  json_annotation: ^4.9.0
  permission_handler: ^12.0.0+1
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.5.0
  custom_lint: ^0.7.5
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  lm_labs_flutter_lints: ^0.4.0
  riverpod_generator: ^2.6.5
  riverpod_lint: ^2.6.5

flutter:
  uses-material-design: true
