name: lm_labs_utils
description: "Reusable utilities for Flutter apps, packages, and plugins to encourage good coding practices"
repository: https://github.com/glemartret/lm_labs_utils
issue_tracker: https://github.com/glemartret/lm_labs_utils/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
version: 3.0.0

environment:
  sdk: ">=3.13.0 <4.0.0"
  flutter: ">=3.47.0"

dependencies:
  connectivity_plus: ^7.3.1
  cupertino_ui: any
  dio: ^5.11.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.4.2
  i18n_extension: ^15.1.1
  json_annotation: ^4.12.0
  material_ui: any
  permission_handler: ^13.0.1
  riverpod_annotation: ^4.0.6

dev_dependencies:
  build_runner: ^2.16.0
  flutter_test:
    sdk: flutter
  freezed: ^4.0.0-dev.3
  json_serializable: ^6.14.1
  lm_labs_flutter_lints: ^3.0.1
  riverpod_generator: ^4.0.8
  riverpod_lint: ^3.1.8

flutter:
  uses-material-design: true
