name: lm_labs_utils
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  connectivity_plus: ^6.0.3
  dio: ^5.5.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.2
  hooks_riverpod: ^2.5.1
  i18n_extension: ^12.0.1
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  extreme_flutter_lints:
    git:
      url: git@github.com:glemartret/extreme_flutter_lints.git
      ref: latest
  flutter_test:
    sdk: flutter
  freezed: ^2.5.4
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.2
  riverpod_lint: ^2.3.12

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true
