name: lm_labs_utils
description: "Reusable utilities for Flutter apps, packages, and plugins to encourage good coding practices"
repository: https://github.com/glemartret/lm_labs_utils
issue_tracker: https://github.com/glemartret/lm_labs_utils/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
version: 2.0.0

environment:
  sdk: ">=3.9.2 <4.0.0"
  flutter: ">=3.35.3"

dependencies:
  connectivity_plus: ^6.1.5
  dio: ^5.9.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^3.1.0
  hooks_riverpod: ^3.0.0
  i18n_extension: ^15.0.5
  json_annotation: ^4.9.0
  permission_handler: ^12.0.1
  riverpod_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.8.0
  custom_lint: ^0.8.1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.11.1
  lm_labs_flutter_lints: ^0.4.0
  riverpod_generator: ^3.0.0
  riverpod_lint: ^3.0.0

dependency_overrides:
  test_api: ^0.7.7

flutter:
  uses-material-design: true
