name: lm_labs_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  connectivity_plus: ^5.0.2
  dio: ^5.4.0
  easy_debounce: ^2.0.3
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  go_router: ^12.1.1
  hooks_riverpod: ^2.4.9
  i18n_extension: ^10.0.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  extreme_flutter_lints:
    git:
      url: git@github.com:glemartret/extreme_flutter_lints.git
      ref: v0.0.3
  flutter_native_splash: ^2.3.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  go_router_builder: ^2.3.4
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/flutter_logo.png
  android_12:
    color: "#ffffff"
    image: assets/images/flutter_logo.png
  info_plist_files:
    - 'ios/LmLabsApp/Info.plist'