name: Create Tag

on:
  push:
    branches:
      - main
jobs:
  tags:
    runs-on: ubuntu-latest
    steps:
      - uses: peiffer-innovations/actions-dart-version-autotag@v1
        with:
          token: ${{ secrets.TAG_TOKEN }}
      - uses: actions/checkout@v2
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest